// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeyitnameWebSite.Data;

#nullable disable

namespace SeyitnameWebSite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251121182301_AddIletisimBilgileri2")]
    partial class AddIletisimBilgileri2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("SeyitnameWebSite.Data.Baglanti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Baglantilar");
                });

            modelBuilder.Entity("SeyitnameWebSite.Data.IletisimBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesaj")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IBilgiler");
                });
#pragma warning restore 612, 618
        }
    }
}
